### ISSUE TITLE
TensorFlowException TF_INVALID_ARGUMENT "No OpKernel was registered to support Op 'Reshape' with these attrs.

### ISSUE THREAD

**Issue by holdenlee** [tensorflow/haskell#78]
I can't get `reshape` to work. In the tensorflow-mnist example (https://github.com/tensorflow/haskell/blob/master/tensorflow-mnist/app/Main.hs) if I replace
```
let hiddenZ = (images `TF.matMul` hiddenWeights) `TF.add` hiddenBiases
```
with 
```
let hiddenZ = ((TF.reshape images (TF.vector [batchSize, numPixels])) `TF.matMul` hiddenWeights) `TF.add` hiddenBiases
```
(which should have no effect because the shape is the same), I get the following error.
```
Main: TensorFlowException TF_INVALID_ARGUMENT "No OpKernel was registered to support Op 'Reshape' with these attrs.  Registered devices: [CPU], Registered kernels:\n  device='GPU'; T in [DT_COMPLEX128]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_COMPLEX64]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_INT8]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_UINT8]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_INT16]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_UINT16]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_INT64]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_DOUBLE]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_FLOAT]; Tshape in [DT_INT32]\n  device='GPU'; T in [DT_HALF]; Tshape in [DT_INT32]\n  device='CPU'; Tshape in [DT_INT32]\n\n\t [[Node: Reshape_27 = Reshape[T=DT_FLOAT, Tshape=DT_INT64](Placeholder_0:0, Const_26:0)]]"
Process exited with ExitFailure 1: /home/optml/holdenl/tensorflow-haskell/.stack-work/install/x86_64-linux-dkd1ce2ff9c9560b648268df668d177711/lts-6.2/7.10.3/bin/Main
```

**Comment by blackgnezdo** [comment]
Looks like a fallout from using Int64 for dimensions. Apparently Reshape is not implemented for Int64 shapes.

We want: [[Node: Reshape_27 = Reshape[T=DT_FLOAT, Tshape=*DT_INT64*](Placeholder_0:0, Const_26:0)]]"
Yet the only possible match is:  device='CPU'; Tshape in [*DT_INT32*]

**Comment by judah** [comment]
It looks like the kernel is more restrictive than the op (which allows int32 and int64):
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reshape_op.cc#L54
https://github.com/tensorflow/tensorflow/blob/1a0742f6a7a06ff54481385b5c51094b0fef8cf3/tensorflow/core/ops/array_ops.cc#L1555

See discussion [here](https://github.com/tensorflow/tensorflow/issues/5886) which previously moved this error from runtime to graph construction.

**Comment by anonym24** [comment]
Do I have similar issue? 

```
InvalidArgumentError (see above for traceback): No OpKernel was registered to support         Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

```


Happens when try to train on Windows:

```
$ python "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_r              etraining\retrain.py" \
>   --image_dir "D:\Oleg\Train\_TensorFlow train\images" \
>   --learning_rate=0.0005 \
>   --testing_percentage=15 \
>   --validation_percentage=15 \
>   --train_batch_size=32 \
>   --validation_batch_size=-1 \
>   --flip_left_right True \
>   --random_scale=30 \
>   --random_brightness=30 \
>   --eval_step_interval=100 \
>   --how_many_training_steps=1000 \
>   --architecture mobilenet_1.0_128_quantized
>> Downloading mobilenet_v1_1.0_128_frozen.tgz 100.0%--- Logging error ---
Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "D:\ProgramFiles\Conda\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 339, in maybe_download_and_extract
    'bytes.')
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\tf_logging.        py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: 'Successfully downloaded'
Arguments: ('mobilenet_v1_1.0_128_frozen.tgz', 19169380, 'bytes.')
INFO:tensorflow:Looking for images in 'car'
INFO:tensorflow:Looking for images in 'road'

Traceback (most recent call last):
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1327, in _do_call
    return fn(*args)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1297, in _run_fn
    self._extend_graph()
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1358, in _extend_graph
    self._session, graph_def.SerializeToString(), status)
  File "D:\ProgramFiles\Conda\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\errors_imp        l.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was register        ed to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Regist        ered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1047, in main
    sess.run(init)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 895, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1321, in _do_run
    options, run_metadata)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\client\session.py",         line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was register        ed to support Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Regist        ered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

Caused by op 'MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1', defined at:
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\platform\app.py", li        ne 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 984, in main
    create_model_graph(model_info))
  File "D:\Oleg\Train\_TensorFlow train\tensorflow\tensorflow\examples\image_retrainin        g\retrain.py", line 282, in create_model_graph
    model_info['resized_input_tensor_name'],
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\importer.p        y", line 313, in import_graph_def
    op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", l        ine 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\ProgramFiles\Conda\lib\site-packages\tensorflow\python\framework\ops.py", l        ine 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support         Op 'Dequantize' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  <no registered kernels>

         [[Node: MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1 = Dequantize[        T=DT_QUINT8, mode="MIN_FIRST"](MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1        _quantized_const, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_mi        n, MobilenetV1/Logits/Conv2d_1c_1x1/weights/read/_1__cf__1_quantized_max)]]

2017-09-20 11:00:36.555015: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compi        led to use AVX instructions, but these are available on your machine and could speed u        p CPU computations.
2017-09-20 11:00:36.555034: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compi        led to use AVX2 instructions, but these are available on your machine and could speed         up CPU computations.
2017-09-20 11:00:37.459748: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:        
name: GeForce 940MX
major: 5 minor: 0 memoryClockRate (GHz) 1.2415
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-20 11:00:37.459766: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2017-09-20 11:00:37.459770: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2017-09-20 11:00:37.459795: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36        \tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/g        pu:0) -> (device: 0, name: GeForce 940MX, pci bus id: 0000:01:00.0)

```
